name: deploy to a test instance
on:
  push:
    branches: [ development ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CICD2_HOST }}
        username: ${{ secrets.CICD2_USERNAME }}
        key: ${{ secrets.CICD2_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
         cd /var/www/art_refferal_web
         sudo git pull origin development
         sudo php artisan optimize
         sudo php artisan config:cache
         sudo php artisan config:clear
